#!/bin/sh

PUBKEY='./public_key.pem'
TMP="tmp_`date "+%Y%m%d%H%M%S"`"

# make a pair of keys
openssl genrsa 4096 > private_key.pem 2> /dev/null
openssl rsa -in private_key.pem -pubout > ${PUBKEY}  2> /dev/null


if [ ! -e ${PUBKEY} ];then
  echo "${PUBKEY} is not exists"
  exit 1
fi

filename='s_file'

if [ -e ${filename} ];then
  echo "${filename} is exists."
  echo
  CMD="rm -i ${filename}"
  echo ${CMD}
  ${CMD}
  echo
  echo "terminated."
  exit
fi

read -sp "Password: " pass
echo
read -sp "Re-type : " pass2
echo

if [ ${pass} = ${pass2} ]; then
  echo "${pass}" | tr -d '\n' > ${TMP}
  cat ${TMP} | openssl rsautl -encrypt -pubin -inkey "${PUBKEY}" > ${filename}
  rm ${TMP}
  chmod 400 ${filename}
  echo
  echo "Output:"
  echo "- ${filename}"
  echo "- private_key.pem"
  echo "- public_key.pem"
else
  echo "Incorrect Password"
fi

exit 0
